const vendorNameKey = "VENDOR_NAME";
const vendorProfileURLKey = "VENDOR_URL";
const vendorPlaceKey = "VENDOR_PLACE";
const vendorCityKey = "VENDOR_CITY";
const vendorStateKey = "VENDOR_STATE";
const vendorPincodeKey = "VENDOR_PINCODE";
const vendorProfessionKey = "VENDOR_PROFESSION";
const vendorDescriptionKey = "VENDOR_DESCRIPTION";
// const vendorRatingKey = "VENDOR_RATING";